(cl:defpackage taticoma_msgs-msg
  (:use )
  (:export
   "<BODYCOMMAND>"
   "BODYCOMMAND"
   "<BODYSTATE>"
   "BODYSTATE"
   "<GAITCOMMAND>"
   "GAITCOMMAND"
   "<LEGIKREQUEST>"
   "LEGIKREQUEST"
   "<LEGJOINTSSTATE>"
   "LEGJOINTSSTATE"
   "<LEGPOSITIONSTATE>"
   "LEGPOSITIONSTATE"
   "<LEGSJOINTSSTATE>"
   "LEGSJOINTSSTATE"
   "<TELEOPCOMMAND>"
   "TELEOPCOMMAND"
   "<TELEOPSERIAL>"
   "TELEOPSERIAL"
  ))

