// Generated by gencpp from file taticoma_msgs/GetLegIKSolver.msg
// DO NOT EDIT!

#ifndef TATICOMA_MSGS_MESSAGE_GETLEGIKSOLVER_H
#define TATICOMA_MSGS_MESSAGE_GETLEGIKSOLVER_H

#include <ros/service_traits.h>

#include <taticoma_msgs/GetLegIKSolverRequest.h>
#include <taticoma_msgs/GetLegIKSolverResponse.h>

namespace taticoma_msgs {

struct GetLegIKSolver {

    typedef GetLegIKSolverRequest Request;
    typedef GetLegIKSolverResponse Response;
    Request request;
    Response response;

    typedef Request RequestType;
    typedef Response ResponseType;

}; // struct GetLegIKSolver
} // namespace taticoma_msgs

namespace ros {
namespace service_traits {

    template <>
    struct MD5Sum<::taticoma_msgs::GetLegIKSolver> {
        static const char* value() {
            return "aab6d4778f2d7a09001d31408c116ed3";
        }

        static const char* value(const ::taticoma_msgs::GetLegIKSolver&) { return value(); }
    };

    template <>
    struct DataType<::taticoma_msgs::GetLegIKSolver> {
        static const char* value() {
            return "taticoma_msgs/GetLegIKSolver";
        }

        static const char* value(const ::taticoma_msgs::GetLegIKSolver&) { return value(); }
    };

    // service_traits::MD5Sum< ::taticoma_msgs::GetLegIKSolverRequest> should match
    // service_traits::MD5Sum< ::taticoma_msgs::GetLegIKSolver >
    template <>
    struct MD5Sum<::taticoma_msgs::GetLegIKSolverRequest> {
        static const char* value() {
            return MD5Sum<::taticoma_msgs::GetLegIKSolver>::value();
        }
        static const char* value(const ::taticoma_msgs::GetLegIKSolverRequest&) {
            return value();
        }
    };

    // service_traits::DataType< ::taticoma_msgs::GetLegIKSolverRequest> should match
    // service_traits::DataType< ::taticoma_msgs::GetLegIKSolver >
    template <>
    struct DataType<::taticoma_msgs::GetLegIKSolverRequest> {
        static const char* value() {
            return DataType<::taticoma_msgs::GetLegIKSolver>::value();
        }
        static const char* value(const ::taticoma_msgs::GetLegIKSolverRequest&) {
            return value();
        }
    };

    // service_traits::MD5Sum< ::taticoma_msgs::GetLegIKSolverResponse> should match
    // service_traits::MD5Sum< ::taticoma_msgs::GetLegIKSolver >
    template <>
    struct MD5Sum<::taticoma_msgs::GetLegIKSolverResponse> {
        static const char* value() {
            return MD5Sum<::taticoma_msgs::GetLegIKSolver>::value();
        }
        static const char* value(const ::taticoma_msgs::GetLegIKSolverResponse&) {
            return value();
        }
    };

    // service_traits::DataType< ::taticoma_msgs::GetLegIKSolverResponse> should match
    // service_traits::DataType< ::taticoma_msgs::GetLegIKSolver >
    template <>
    struct DataType<::taticoma_msgs::GetLegIKSolverResponse> {
        static const char* value() {
            return DataType<::taticoma_msgs::GetLegIKSolver>::value();
        }
        static const char* value(const ::taticoma_msgs::GetLegIKSolverResponse&) {
            return value();
        }
    };

} // namespace service_traits
} // namespace ros

#endif // TATICOMA_MSGS_MESSAGE_GETLEGIKSOLVER_H
