// Generated by gencpp from file taticoma_msgs/TeleopSerial.msg
// DO NOT EDIT!


#ifndef TATICOMA_MSGS_MESSAGE_TELEOPSERIAL_H
#define TATICOMA_MSGS_MESSAGE_TELEOPSERIAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace taticoma_msgs
{
template <class ContainerAllocator>
struct TeleopSerial_
{
  typedef TeleopSerial_<ContainerAllocator> Type;

  TeleopSerial_()
    : axes()
    , a_buttons()
    , p_buttons()
    , buttons()
    , mode(0)
    , gait_mode(0)  {
      axes.assign(0);

      a_buttons.assign(0);

      p_buttons.assign(0);

      buttons.assign(0);
  }
  TeleopSerial_(const ContainerAllocator& _alloc)
    : axes()
    , a_buttons()
    , p_buttons()
    , buttons()
    , mode(0)
    , gait_mode(0)  {
  (void)_alloc;
      axes.assign(0);

      a_buttons.assign(0);

      p_buttons.assign(0);

      buttons.assign(0);
  }



   typedef boost::array<uint8_t, 4>  _axes_type;
  _axes_type axes;

   typedef boost::array<uint8_t, 2>  _a_buttons_type;
  _a_buttons_type a_buttons;

   typedef boost::array<uint8_t, 2>  _p_buttons_type;
  _p_buttons_type p_buttons;

   typedef boost::array<uint8_t, 2>  _buttons_type;
  _buttons_type buttons;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _gait_mode_type;
  _gait_mode_type gait_mode;





  typedef boost::shared_ptr< ::taticoma_msgs::TeleopSerial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::taticoma_msgs::TeleopSerial_<ContainerAllocator> const> ConstPtr;

}; // struct TeleopSerial_

typedef ::taticoma_msgs::TeleopSerial_<std::allocator<void> > TeleopSerial;

typedef boost::shared_ptr< ::taticoma_msgs::TeleopSerial > TeleopSerialPtr;
typedef boost::shared_ptr< ::taticoma_msgs::TeleopSerial const> TeleopSerialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::taticoma_msgs::TeleopSerial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::taticoma_msgs::TeleopSerial_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace taticoma_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'taticoma_msgs': ['/home/ubuntu/TATICOMA/ROS/src/taticoma_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::taticoma_msgs::TeleopSerial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::taticoma_msgs::TeleopSerial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::taticoma_msgs::TeleopSerial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::taticoma_msgs::TeleopSerial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::taticoma_msgs::TeleopSerial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::taticoma_msgs::TeleopSerial_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::taticoma_msgs::TeleopSerial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a826112f65f9a91607209418c91cb6b7";
  }

  static const char* value(const ::taticoma_msgs::TeleopSerial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa826112f65f9a916ULL;
  static const uint64_t static_value2 = 0x07209418c91cb6b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::taticoma_msgs::TeleopSerial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "taticoma_msgs/TeleopSerial";
  }

  static const char* value(const ::taticoma_msgs::TeleopSerial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::taticoma_msgs::TeleopSerial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint8[4] axes\n"
"uint8[2] a_buttons\n"
"uint8[2] p_buttons\n"
"uint8[2] buttons\n"
"\n"
"uint8 mode\n"
"uint8 gait_mode\n"
"\n"
"\n"
;
  }

  static const char* value(const ::taticoma_msgs::TeleopSerial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::taticoma_msgs::TeleopSerial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axes);
      stream.next(m.a_buttons);
      stream.next(m.p_buttons);
      stream.next(m.buttons);
      stream.next(m.mode);
      stream.next(m.gait_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TeleopSerial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::taticoma_msgs::TeleopSerial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::taticoma_msgs::TeleopSerial_<ContainerAllocator>& v)
  {
    s << indent << "axes[]" << std::endl;
    for (size_t i = 0; i < v.axes.size(); ++i)
    {
      s << indent << "  axes[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.axes[i]);
    }
    s << indent << "a_buttons[]" << std::endl;
    for (size_t i = 0; i < v.a_buttons.size(); ++i)
    {
      s << indent << "  a_buttons[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.a_buttons[i]);
    }
    s << indent << "p_buttons[]" << std::endl;
    for (size_t i = 0; i < v.p_buttons.size(); ++i)
    {
      s << indent << "  p_buttons[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.p_buttons[i]);
    }
    s << indent << "buttons[]" << std::endl;
    for (size_t i = 0; i < v.buttons.size(); ++i)
    {
      s << indent << "  buttons[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.buttons[i]);
    }
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "gait_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gait_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TATICOMA_MSGS_MESSAGE_TELEOPSERIAL_H
